### ISSUE TITLE
geht nicht in Kodi 20.1

### ISSUE THREAD

**Issue by GTSFWL** [b-jesch/service.displayswitch#1]
hallo leider geht das skipt nicht mehr in Kodi 20.1

`2023-02-16 19:11:30.867 T:967     error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'xbmc' has no attribute 'translatePath'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/service.displayswitch/service.py", line 17, in <module>
                                                       addon_path = xbmc.translatePath(addon.getAddonInfo('path'))
                                                                    ^^^^^^^^^^^^^^^^^^
                                                   AttributeError: module 'xbmc' has no attribute 'translatePath'
                                                   -->End of Python script error report<--`

Bitte um hilfe

**Comment by b-jesch** [comment]
Bin zur Zeit im KH. Wird frühestens nächstes WE.

**Comment by GTSFWL** [comment]
Hallo danke für Antwort. Kein Problem, Gesundheit ist wichtiger. Würde mich
trotzdem freuen wenn sie das hinbekommen,wenn sie wieder Genesen sind.Dann
erst mal gute Besserung.

Mfg GTS

Birger Jesch ***@***.***> schrieb am Sa., 22. Apr. 2023,
18:27:

**Comment by b-jesch** [comment]
Has been fixed and is available now in Nerdsrepo (both Krypton and Matrix+ versions).

**Comment by GTSFWL** [comment]
Hallo
Danke für die Bearbeitung, habe noch einen kleine fehler entdeckt, in der
addon.xml
<import addon="xbmc.python" version="2.25.0"/> sie muss geändert werden in
Version  "3.0.0"
dann geht alles in Matrix und Nexus

MFG Rettig

Am Do., 27. Apr. 2023 um 14:04 Uhr schrieb Birger Jesch <
***@***.***>:

**Comment by b-jesch** [comment]
Du musst nur anstelle des Master-Branches oben den Matrix -Branch auswählen und installieren, dann klappt das auch mit der Python -Version... 😁
